"
Visitar 

"
Class {
	#name : #Visitor,
	#superclass : #Object,
	#category : #'JuegoLaberinto-Visitor'
}

{ #category : #'as yet unclassified' }
Visitor >> visitarArmario:unArmario [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarBomba:unaBomba [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarHabitacion:unaHab [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPared:unaPared [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarPuerta:unaPuerta [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]

{ #category : #'as yet unclassified' }
Visitor >> visitarTunel:unTunel [
"No hacer nada / implementacion predeterminada para todas las subclases / forzar a que las subclases lo implementen"
]
